# Generated by Django 2.0.8 on 2018-09-21 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('texto', models.TextField()),
                ('setor', models.CharField(max_length=50)),
                ('data', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
